### ISSUE TITLE
Did anyone managed to install and run this code?

### ISSUE THREAD

**Issue by Michlozz** [Huang-CL/Magrathea#6]
Hi,
I'm trying few days to go over the instructions and install this code. 
I tried using windows' buiIt-in Ubuntu, I tried on remote server.  installed cygwin with gsl; nothing works! 

On the remote uni server I get " ... is not in the sudoers file.  This incident will be reported."
On Cygwin I get "-bash: sudo: command not found"
On windows "Ubuntu" terminal I get:
"g++  -o src/phase.o -c src/phase.cpp -std=c++0x -O3 -Wall
In file included from src/EOS.h:4:0,
                 from src/phase.h:4,
                 from src/phase.cpp:1:
src/define.h:13:10: fatal error: gsl/gsl_odeiv2.h: No such file or directory
 #include <gsl/gsl_odeiv2.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:20: recipe for target 'src/phase.o' failed
make: *** [src/phase.o] Error 1

"

Did anyone managed with it? Any solution?

**Comment by Huang-CL** [comment]
1. You received the error on the remote server because you don't have root access to the server.  It means you can't install `gsl` globally for all users, e.g. under `/usr/local/bin/`. However, you can always install the `gsl` package on the server for yourself.  The steps are described in detail under the `INSTALL` file under the downloaded gsl package. For short, instead of `sudo ./configure`, you use `./configure --prefix=PREFIX`, where PREFIX is the path to the location you plan to install and it must be an absolute path.  For example, `./configure --prefix=/home/youraccountname`.
Then `cd` to the directory you plan to install the package, you can install it with `make` and `make install`.
If the server is a university cluster, most likely the `gsl` package has already been installed on it. Depending on the environment of the cluster, you can locate `gsl` with `module avail` or `module available`. You can then load the package with `module load gsl` or something equivalent.
After installing `gsl` locally, you can follow step 2 in the quick start section of the README to set up MAGRATHEA.

2. I'm not familiar with Cygwin. My guess is that you encounter a similar problem as the one you have on the server. Please try the steps I described above. If you still fail, my collaborator may be able to provide more specific guidance.
 
3. In wsl system, have you modified the `Makefile` according to the step 2 in the quick start section of the README? What is the output of `gsl-config --cflags` and `gsl-config --libs`, and what does the Makefile look like after your edits?

**Comment by Michlozz** [comment]
Thank you Huang-CL. I'm still struggling with the manual. 
On the University server, I type:` gsl-config --libs` and then I get:
`-lgsl -lgslcblas -lm`
Afterwards, I type: `module load gsl`.  Then I type again: `gsl-config --cflags` I get:
`-L/powerapps/share/gsl/lib -lgsl -lgslcblas -lm`
Then I type `gsl-config --prefix` I get:
`/powerapps/share/gsl`
Does it ring a bell? Does it mean the module was loaded?
 
Next I do `git clone https://github.com/Huang-CL/Magrathea.git`; it copied this folder to the server. done. 
And then I stuck again. The instructions say to modify "make" file. I guess the meaning is to modify the lines:
1. CFLAGS= -std=c++0x -O3 -Wall #-I ~/Downloads/gsl/include
2. LDFLAGS= -L/usr/local/lib -lgsl -lgslcblas -lm #-L ~/Downloads/gsl/lib
But I don't understand what to do there.  
`gsl-config --cflags` gives` -I/usr/include`; Do you know what does it mean? For me all of those are some mystery symbols and random letters.

Thank you very much.

**Comment by Huang-CL** [comment]
I'm a bit confused about the output you reported.
`-L/powerapps/share/gsl/lib -lgsl -lgslcblas -lm` can only be the output of the command `gsl-config --libs`. I'm not sure how could you receive this output with the command `gsl-config --cflags`.
Now, assuming `gsl-config --libs` gives you `-L/powerapps/share/gsl/lib -lgsl -lgslcblas -lm`, I would assume the output of `gsl-config --cflags` should be `-I/powerapps/share/gsl/include`.  So it's a bit weird that you got `-I/usr/include`. Are you talking about two different machines?

Assuming the output of `gsl-config --cflags` is `-I/powerapps/share/gsl/include`. Then the two lines in the Makefile should look like
`CFLAGS= -std=c++0x -O3 -Wall -I/powerapps/share/gsl/include`
`LDFLAGS= -L/powerapps/share/gsl/lib -lgsl -lgslcblas -lm`

If the output of `gsl-config --cflags` is `-I/usr/include` and `gsl-config --libs` gives you `-L/usr/local/lib -lgsl -lgslcblas -lm`, the two lines should be
`CFLAGS= -std=c++0x -O3 -Wall`
`LDFLAGS= -L/usr/local/lib -lgsl -lgslcblas -lm`

**Comment by Michlozz** [comment]
You are totally right, I confused the outputs.
So it worked! I got the "planet" file and it runs. 
Thank you very much, I hope it will be useful to my research (I will not forget to cite you).
