### ISSUE TITLE
Adding temperature dependent tabulated EOS

### ISSUE THREAD

**Issue by Michlozz** [Huang-CL/Magrathea#8]
What I'm trying to do is to add to the program a new feature: to read from temperature dependent EOS, that I have as a table.
The format of my table is as follows:

T rho P
11.605 2.51188643150958e-13 4.28547303990553e-16
11.605 3.16227766016838e-13 4.28547303990553e-16
11.605 3.98107170553497e-13 4.28547303990553e-16
11.605 5.01187233627271e-13 4.28547303990553e-16
11.605 6.30957344480194e-13 4.28547303990553e-16
...
14.6098294038713 2.51188643150958e-13 5.45304484892599e-16
14.6098294038713 3.16227766016838e-13 5.45304484892599e-16
14.6098294038713 3.98107170553497e-13 5.45304484892599e-16
14.6098294038713 5.01187233627271e-13 5.45304484892599e-16
14.6098294038713 6.30957344480194e-13 5.45304484892599e-16
...
...
581627.784624449 2.51188643150958e-13 6.96820850132487e-10
581627.784624449 3.16227766016838e-13 7.45909582615774e-10
581627.784624449 3.98107170553497e-13 9.38469438957118e-10
581627.784624449 5.01187233627271e-13 1.18077741816094e-09
581627.784624449 6.30957344480194e-13 1.48568922527515e-09
...
1160500 79.4328234724281 340332.523678576
1160500 100 474344.468455402

------
In that way for every pair (T,rho) in a table I get one P.

My idea is pretty simple:  Now the code is able to read EOS of (rho,P). The only thing I have to add is a function that will read T and create a table of (rho,P) for every layer (as the planet is not isothermic). I call may EOS (of rock) "QEOS". 
The function reads QEOS_full.txt (a file with T, rho. P) and creates a file for a given temperature T:

```
void QEOS_build(double T, const int size) {
	// "size" is the length of the entire table. 

	double P_line = 0.0, T_line = 0.0, rho_line = 0.0, tmp = 0.0, Tlow = 0.0, Thigh = 0.0, T0 = 0.0;
	double P_table[size], T_table[size], rho_table[size];
	double rhohigh[size], rholow[size], Phigh[size], Plow[size], rhoiterp[size], Piterp[size]; //Note that not entire array is used. 
	

	FILE* fp = fopen("tabulated/QEOS_full.txt", "r");
	int j, i, blocksize, jbrake;

	if (!fp) {
		perror("fopen");
		return;
	}

	char line[512];

	if (!fgets(line, sizeof line, fp) || !strstr(line, "T rho P")) {
		fprintf(stderr, "Invalid or missing header.\n");
		return;
	}
	j = 0;


	while (fgets(line, sizeof line, fp)) {
		if (3 == sscanf(line, "%lf%lf%lf", &T_line, &rho_line, &P_line)) {
			T_table[j] = T_line;
			rho_table[j] = rho_line;
			P_table[j] = P_line;
			j = j + 1;

		}
	}



	fclose(fp);
	T0 = T_table[0];

	for (j = 0; j < size; j++) {
		tmp = T_table[j];
		if (tmp > T0) {
			break;
		}

	}	// j breaks so [0--j] is one block size

	blocksize = j;


	for (j = 0; j < size; j++) {
		tmp = T_table[j];
		if (tmp > T) {
			break;
		}

	} //Find T in table that is larger than given T

	Tlow = T_table[j - 1];
	Thigh = T_table[j];
	jbrake = j; // a place there two blocks meet



	i = 0;
	for (j = jbrake; j <= blocksize + jbrake - 1; j++) {
		Phigh[i] = P_table[j];
		rhohigh[i] = rho_table[j];
		i++;

	}

	i = 0;
	for (j = jbrake - blocksize ; j <= jbrake; j++) {
		Plow[i] = P_table[j];
		rholow[i] = rho_table[j];
		i++;

	}
	for (j = 0; j < blocksize ; j++) { //intepulation between two blocks
		Piterp[j] = Plow[j] + (Phigh[j] - Plow[j])  / (Thigh - Tlow) * (T - Tlow); //Not useful in my case
		rhoiterp[j] = rholow[j] + (rhohigh[j] - rholow[j]) / (Thigh - Tlow) * (T - Tlow); 

	}


	
	ofstream myfile; //save as new EOS table:

	myfile.open("tabulated/QEOS.txt");
	
	
	myfile << "rho (g/cm^-3)	P (GPa); T="<<T<<"\n";
	for (j = 0; j < blocksize; j++) {
		myfile << std::scientific << std::setprecision(10) <<rhoiterp[j]<< " " ;
		myfile<< std::scientific << std::setprecision(6) << Piterp[j];
		if(j < blocksize - 1) myfile << "\n";
		
		
	}

	myfile.close();

	 
}
```
This function is not extremely well written from the point of c++, but it does the work of creating a table for a given T.

Now, the only thing left is to integrate this table into the program. So I added it to the end of  the file _phase.cpp_, there I repalced the line "return Si_Pv;" with two lines: "QEOS_build(T, 7497); " and "return Si_QEOS;". 
The file _EOSlist.cpp_ was modified: I added "EOS *Si_QEOS = new EOS("Si (QEOS)", "./tabulated/QEOS.txt");" and added the new EOS to the list.

now.... for some reason this doen't work. Maybe it's my clumsy wring style in C, but for some reason the code seem to fail to read my EOS.

My guess is a different format  of P-rho relations, but also it might be some wrong place to add my new function.

[QEOS_full.txt](https://github.com/Huang-CL/Magrathea/files/10004007/QEOS_full.txt)
[QEOS.txt](https://github.com/Huang-CL/Magrathea/files/10004010/QEOS.txt)

**Comment by Huang-CL** [comment]
I'm sorry, but I'm afraid your method doesn't work.  The program read in "QEOS.txt" only once at the very begining of the code.  In your case, QEOS.txt is created/updated during the code is running. The new table does not impact the current run.  In addition, since the QEOS.txt is created/updated every step in the mantle layer, it is very inefficient. 

Depends on your task, there are two solutions. 
(1) It's unlikely that you can calculate a temperature gradient using your tabulated EOS. So I guess you will apply an isothermal mantle layer. If it is the case and you only plan to test the profile at a few constant temperatures, you can create a few temperature independent EOS tables for each temperature you plan to study. 

(2) If you want to test a more continuous temperature, or you somehow created a temperature gradient, you may want to go a different path. You should create a new `eqntype` to interpolate your EOS table. If you prefer to interpolate in the space of (P, T) and get density, you can add your eqntype in the function `double density(double P, double T, double rho_guess);` at line 856-981 in `EOS.cpp`.  You can mimic the code for eqntype=5 at line 874-893 to accomplish your goal.  Otherwise, if you prefer to interpolate in the space of (rho, T) and get pressure, you can add your code to `double Press (double rho, double T);` at line 1195-1237.

If neither of these options can fulfill your request, please provide more details ragarding your goal.

**Comment by Michlozz** [comment]
Thanks.
Our goal is to use an EOS of water-rock homogeneous mixture with a given proportions (which I will manually choose in the beginning of a run), as the envelope. In this substance is P-rho relations are temperature depended, so I can't assume isothermic interiors. 
T-profile of a planet isn't flat, but has a gradual decrease of temperature towards the surface. So "path (2)" is my way. The table I have provides P from (T,rho) space, so I'm in "double EOS::Press(double rho, double T)", and I see a switch of "geteqntype" there.  I can add "case 5" to the list, there I will call for my function. Something like 
```
 case 5:
     P=QEOS(T,rho);
     break;"
```
So, first: where do I force the eq-type to be equal to 5?
Second, how do I "path" the code to go to "EOS::Press" function? My guess would be via "EOS* find_Si_phase(double P, double T)" in _phase.cpp_ file.
Third, the program is able to read EOS-table only once in the beginning of the run. This is the reason my previous algorithm wouldn't work. Right? So if I understood you, here the idea is kind of "crack" the program in a different place, and instead of calculating P (like in "Keane(rho)" or Holzapfel(rho) ), we will read the table, and do a double interpolation (find P corresponding to given (T,rho) ).
Did I get the idea correctly?

**Comment by Huang-CL** [comment]
The part you added to the Press function is correct. However, I suggest you to pull the most recent commit (e3d12b5) from the master branch because I just noticed that I messed up the `eqntype` 5 and 7 in the code.  There are only a few changes to the code in this commit. You can either merge it with your own fork, or view the changes I made in this commit and change manually in your own fork.  If you rather not make the change, please assign `eqntype` to 7 instead of 5 for the EOS you added.

Then, to create the new EOS, you should use this constructor function instead.
`EOS(string phaseinput, double params[][2], int length);`

So the part added in the EOSlist.cpp should be something like
```
double Si_QEOS_array[][2] = {{0,5}, {1, 40}, {5, mSi}};
EOS *Si_QEOS = new EOS("Si (QEOS)", Si_QEOS_array, sizeof(Si_QEOS_array)/2/sizeof(Si_QEOS_array[0][0]));
```

The {0,5} part assign the `eqntype` to 5. 40 is the V0 in cm^3 / mol, and mSi is molecular weight in  g / mol.

-----
I haven't finished this answer yet. I'll edit this answer later to include the following information:
`density (P,T)` function performs better than `Press (rho,T)` function. So I suggest you use `density (P,T)` if possible.
I'll provide some more information regarding how to manually provide a temperature gradient if you have not yet completed that part.

**Comment by Michlozz** [comment]
Thank you!
I have added a new function that mimics a calculation of rho form (P,T) to _EOS.cpp_. This is not the best solution from a point of view of code's performance. The best one would be to read T_vec, P_vec, and rho_vec once, and store them as global variables. But this is a bit beyond my level, and I think I can work with code that runs 8-10 minutes instead of few seconds. 

Seems like it works (at least there is output file, and there is a reading from an EOS file). But you are totally right: the envelope is isothermal (see file attached), which makes my function almost irrelevant. 
So now, to the next mission: gradual change of T. 
I see _dTdP_gas_ in EOSlist.cpp file, and I have to make sure I uderstood. The function _double dTdP_gas(double P, double T)_  have two input variables and one output. What is the physical meaning of the output variable? My first guess is that the meaning is as simple as it: **dT/dP= (2T)/(7P)** . Is it right?

In a meanwhile, I tied to add a line` Si_QEOS->modify_dTdP(dTdP_gas);` to EOSlist.cpp. I get a compilation  `error: ‘Si_QEOS’ does not name a type`. I guess I did it in a wrong place.  Were exactly this has to be applied? 

[Structure.txt](https://github.com/Huang-CL/Magrathea/files/10067422/Structure.txt)

**Comment by Huang-CL** [comment]
The function returns the dT/dP, which is the temperature gradient at given pressure and temperature point in the unit of K/&mu;bar. 
As an example, for the ideal gas, dT/dP=(1-1/&gamma;)T/P.  For diatomic gas, &gamma;=5/7, so dT/dP = 2T/(7P). 
You need to create an appropriate formula that suits your EOS.

Have you added `Si_QEOS` into EOSlist.h? If so, make sure you use `make -B` to compile your code every time you modify a .h file.

**Comment by Michlozz** [comment]
I have added *Si_QEOS into EOSlist.h, and try to compile with -B.

I afraid that the place I try to add the function is not correct. Even than I try to use `Si_Pv->modify_dTdP(dTdP_gas);` I get an error massage _‘Si_Pv’ does not name a type_. 

Where exactly this has to be applied? I tried to add the line `Si_Pv->modify_dTdP(dTdP_gas);` in the end of EOSlist.cpp, in the end of EOS.ccp, or in the end of my function _double QEOS(double T, double rho, const int size)_ .  Didn't compile.

**Comment by Huang-CL** [comment]
Sorry, my bad.
Please add `double dTdP_gas(double P, double T);` (or equivalent) to `EOSlist.h`. And then add `Si_Pv->modify_dTdP(dTdP_gas);` to `main.cpp` at e.g. line 30.

**Comment by Michlozz** [comment]
Oh, wow. It worked!
Now, then I try to use my P-T profile, I get an error:
`Error: Failed to set up the radius solver for the first round outside-in integration for 1, 0.5, 0.1, 1e-05`

What is the common reason for bad convergence such as this?

**Comment by Huang-CL** [comment]
One possible cause is that the EOS doesn't behave well at certain regions required for the calculation.  For example, the EOS is very unsmooth, or outputs unphysically high/low density due to extrapolation can lead to this error.  There can be many other causes though. 
To let the code output more error messages, set the `verbose` at line 19 in `main.cpp` to true.  If still can't find any clue, try uncommenting the print command at line 438 in `hydro.cpp`.

**Comment by Michlozz** [comment]
OK, it seem to work. Last question for this issue:
What are the pressure units to code expects then it computes dT/dP?

**Comment by Huang-CL** [comment]
All values are in the cgs unit. The input pressure is in the unit of μbar.  The output value is in the unit of K/μbar.
